version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 5
  ignore:
  - dependency-name: parser
    versions:
    - 3.0.0.0
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 5.0.0
  - dependency-name: database_cleaner
    versions:
    - 2.0.0
    - 2.0.1
  - dependency-name: simplecov
    versions:
    - 0.21.1
