apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: offender-manager-process-movements
spec:
  schedule: "30 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: process-movements
            image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/offender-management/offender-management-allocation-manager:latest
            imagePullPolicy: Always
            command: ['sh', '-c', "bundle exec rake movements:process"]
            envFrom:
              - configMapRef:
                  name: shared-environment
              - secretRef:
                  name: allocation-manager-secrets
            env:
              - name: PROMETHEUS_METRICS
                value: "off"
              - name: POSTGRES_HOST
                valueFrom:
                  secretKeyRef:
                    name: allocation-rds-instance-output
                    key: rds_instance_address
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: allocation-rds-instance-output
                    key: postgres_password
              - name: POSTGRES_NAME
                valueFrom:
                  secretKeyRef:
                    name: allocation-rds-instance-output
                    key: postgres_name
              - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: allocation-rds-instance-output
                    key: postgres_user
              - name: REDIS_URL
                valueFrom:
                  secretKeyRef:
                    name: elasticache-offender-management-allocation-manager-token-cache-preprod
                    key: url
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: offender-manager-delius-import
spec:
  schedule: "15 21 * * 1-5"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: delius-import
              image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/offender-management/offender-management-allocation-manager:latest
              imagePullPolicy: Always
              command: ['sh', '-c', "bundle exec rails r DeliusImportJob.perform_later"]
              envFrom:
                - configMapRef:
                    name: shared-environment
                - secretRef:
                    name: allocation-manager-secrets
              env:
                - name: PROMETHEUS_METRICS
                  value: "off"
                - name: POSTGRES_HOST
                  valueFrom:
                    secretKeyRef:
                      name: allocation-rds-instance-output
                      key: rds_instance_address
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: allocation-rds-instance-output
                      key: postgres_password
                - name: POSTGRES_NAME
                  valueFrom:
                    secretKeyRef:
                      name: allocation-rds-instance-output
                      key: postgres_name
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: allocation-rds-instance-output
                      key: postgres_user
                - name: REDIS_URL
                  valueFrom:
                    secretKeyRef:
                      name: elasticache-offender-management-allocation-manager-token-cache-preprod
                      key: url
          restartPolicy: OnFailure
