inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

AllCops:
  # Exclude anything that isn't really part of our code.
  # rails_helper is excluded because it's full of solecisms, but it's mostly
  # generated code and copy-and-pasted snipets from READMEs.
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - '**/*.gemspec'
    - '**/Rakefile'
    - '**/Vagrantfile'
    - 'app/views/api/**/*.json.jbuilder'
    - 'config/initializers/assets.rb'
    - 'config/unicorn.rb'
    - 'spec/rails_helper.rb'
    - 'lib/tasks/brakeman.rake'
    - 'lib/tasks/elasticsearch.rake'
    - 'spec/dummy/db/**/*'
    - 'config/routes.rb'

Style/MultilineBlockChain:
  Enabled: false

Style/SymbolArray:
  Enabled: false

# Enforce single quotes everywhere except in specs (because there's a lot of
# human text with apostrophes in spec names, and using double quotes for all
# of those is more consistent. There shouldn't be much human-readable text in
# the application code: that is better moved to the locale files.
Style/StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    - 'spec/**/*'

## Don't allow safe assignment in conditions.
Lint/AssignmentInCondition:
  AllowSafeAssignment: false

RSpec/AnyInstance:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Max: 38

RSpec/ExampleLength:
  Max: 95

RSpec/HookArgument:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 13

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 8

RSpec/ScatteredSetup:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/MultilineArrayBraceLayout:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false

Capybara/FeatureMethods:
  Enabled: false

## Below here is the set of (arbitrary) failures against the govuk styles
Style/WordArray:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: false
